version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
         name: Store Version and Image name
         command: |
           echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
           echo 'export IMAGE_NAME=django-role-manager' >> $BASH_ENV
     # with credentials stored in the UI
     - run:
         command: |
           docker build -t breedocker/$IMAGE_NAME:$TAG .
           echo "$PASSWORD" | docker login -u "$USER" --password-stdin
           docker push breedocker/$IMAGE_NAME:$TAG
