jobs:
  build-and-push:
    steps:
      - checkout
      - run:
          name: Store Version and Image name
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=django-role-manager' >> $BASH_ENV 
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t breedocker/$IMAGE_NAME:$TAG
            echo $PASSWORD | docker login -u $USER --password-stdin
            docker push breedocker/$IMAGE_NAME:$TAG
              
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      -  build-and-push:
           context: django-discord-rolemanager
      
