# Generated by Django 2.2.4 on 2019-08-30 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.IntegerField(db_index=True)),
                ('guild_name', models.CharField(blank=True, default='Unknown', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('role_name', models.CharField(blank=True, default='donator', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuildToRoleRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.DiscordGuild')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.DiscordRole')),
            ],
        ),
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('fee', models.FloatField(default=0.0)),
                ('precious', models.BooleanField(default=False)),
                ('last_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('monthly_paid', models.BooleanField(default=False)),
                ('days_until_payment', models.IntegerField(default=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Donator')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedDiscordServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.DiscordGuild')),
            ],
        ),
    ]
