# Generated by Django 2.2.4 on 2019-08-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordguild',
            name='guild_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='discordrole',
            name='role_id',
            field=models.BigIntegerField(),
        ),
    ]
