# Generated by Django 2.2.4 on 2019-08-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='discord_user',
            new_name='DiscordUser',
        ),
        migrations.RenameModel(
            old_name='donations',
            new_name='Donation',
        ),
    ]
