# Generated by Django 2.2.4 on 2019-08-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('donations', '0002_auto_20190828_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
        ),
        migrations.DeleteModel(
            name='DiscordUser',
        ),
    ]
