# Generated by Django 2.2.4 on 2019-08-31 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20190830_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount', unique=True),
        ),
    ]
