# Generated by Django 2.2.4 on 2019-08-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20190831_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='note',
            field=models.CharField(default='', max_length=128),
        ),
    ]
