# Generated by Django 2.2.4 on 2019-08-29 13:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_monthly_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='discord_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='last_payment',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 13, 45, 46, 880781)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='precious',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
        ),
    ]
