# Generated by Django 2.2.4 on 2019-09-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20190901_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='donator',
            name='paid',
            field=models.IntegerField(default=0.0),
        ),
    ]
