# Generated by Django 2.2.4 on 2019-09-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_auto_20190901_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
