# Generated by Django 2.2.4 on 2019-08-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_auto_20190829_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='discord_username',
        ),
    ]
