# Generated by Django 2.2.4 on 2019-09-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_rawdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdonation',
            name='uid',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
