# Generated by Django 2.2.4 on 2019-09-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_rawdonation_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='days_until_payment',
            field=models.IntegerField(default=0),
        ),
    ]
