# Generated by Django 2.2.4 on 2019-09-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_auto_20190902_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='autopay',
            field=models.BooleanField(default=False),
        ),
    ]
