# Generated by Django 2.2.4 on 2019-09-05 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_donator_autopay'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donator',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
