# Generated by Django 2.2.4 on 2019-09-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20190905_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
