# Generated by Django 2.2.8 on 2020-01-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_donator_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
