# Generated by Django 2.2.15 on 2022-02-27 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_auto_20200105_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Donator')),
            ],
        ),
    ]
